// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace codelist0209_0211.Models
{
    public partial class Todo
    {
        public Guid Id { get; set; }
    }
}